config/routes.rb
Wheretowait::Application.routes.draw do

  match '/dashboard' => 'dashboard#index', :as => :user_root

  resources :flagged_words
  resources :questionnaires do
    resources :user_answers
    get :needs_moderation, :on => :collection
  end
  resources :contacts
  resources :user_answers
  resources :answers
  resources :questions
  resources :question_answers
  resources :locations do
    resources :questionnaires
  end

  resources :members
  devise_for :users

  match '/terms' => 'site#terms', :as => :terms
  match '/privacy' => 'site#privacy', :as => :privacy
  match '/about' => 'site#about', :as => :about
  match '/guidelines' => 'site#guidelines', :as => :guidelines
  match '/faq' => 'site#faq', :as => :faq

  root :to => 'site#index'

end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  attr_accessible :questionnaire, :question, :value, :location

  # relationships
  belongs_to :question
  belongs_to :questionnaire
  belongs_to :location

  # validations
  validates :question, :questionnaire, :location, presence: true
  validates :value, :numericality => true

  def self.search(page, per_page)
    paginate :per_page => per_page, :page => page,
             :order => 'created_at DESC'
  end

  # scopes
  scope :by_location, lambda { |location_id| where('location_id = ?', location_id) }
  scope :by_question, lambda { |question_id| where('question_id = ?', question_id) }

end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_filter :verify_credentials_admin

  # GET /user_answers
  # GET /user_answers.json
  def index
    @user_answers = UserAnswer.search(params[:page], 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_answers }
    end
  end

  # GET /user_answers/1
  # GET /user_answers/1.json
  def show
    @user_answer = UserAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_answer }
    end
  end

  # GET /user_answers/new
  # GET /user_answers/new.json
  def new
    @user_answer = UserAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_answer }
    end
  end

  # GET /user_answers/1/edit
  def edit
    @user_answer = UserAnswer.find(params[:id])
  end

  # POST /user_answers
  # POST /user_answers.json
  def create
    @user_answer = UserAnswer.new(params[:user_answer])

    respond_to do |format|
      if @user_answer.save
        format.html { redirect_to @user_answer, notice: 'User answer was successfully created.' }
        format.json { render json: @user_answer, status: :created, location: @user_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @user_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_answers/1
  # PUT /user_answers/1.json
  def update
    @user_answer = UserAnswer.find(params[:id])

    respond_to do |format|
      if @user_answer.update_attributes(params[:user_answer])
        format.html { redirect_to @user_answer, notice: 'User answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_answers/1
  # DELETE /user_answers/1.json
  def destroy
    @user_answer = UserAnswer.find(params[:id])
    @user_answer.destroy

    respond_to do |format|
      format.html { redirect_to user_answers_url }
      format.json { head :no_content }
    end
  end

  private

  def verify_credentials_admin
    # first check if anyone is even checked in
    unless user_signed_in?
      redirect_to new_user_session_path, notice: t(:Need_to_sign_in)
      return
    end
    unless current_user.role=='admin'
      redirect_to root_path, notice: t(:Need_permissions)
    end
  end
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/user_answers/_form.html.erb
<%= form_for(@user_answer, :html => {:role => 'form'}) do |f| %>
    <% if @user_answer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_answer.errors.count, "error") %> prohibited this user_answer from being saved:</h2>

          <ul>
            <% @user_answer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :question %>
      <br/>
      <%= f.collection_select :question, Question.all, :id, :title, {}, {:class => 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :value %>
      <br/>
      <%= f.text_field :value, :class => 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/user_answers/edit.html.erb
<% title 'Editing User Answer' %>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
  </div>
</div>

app/views/user_answers/index.html.erb
<% title 'Listing User Answers' %>

<div class="table-responsive">
  <table class="table table-striped">
    <tr class="table-header">
      <th>Question</th>
      <th>Value</th>
      <th>Created At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @user_answers.each do |user_answer| %>
        <tr>
          <td><%= user_answer.question.title %></td>
          <td><%= user_answer.value %></td>
          <td><%= user_answer.created_at %></td>
          <td><%= link_to 'Show', user_answer %></td>
          <td><%= link_to 'Edit', edit_user_answer_path(user_answer) %></td>
          <td><%= link_to 'Destroy', user_answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

<br/>

<%= link_to 'New User answer', new_user_answer_path %>

<%= will_paginate @user_answers,
                  :renderer => PaginationListLinkRenderer,
                  :previous_label => '&laquo;',
                  :next_label => '&raquo;',
                  :class => 'pagination' %>

app/views/user_answers/new.html.erb
<% title 'New User Answer' %>

<div class="row">
  <div class="col-sm-5">
<%= render 'form' %>
</div>
</div>

app/views/user_answers/show.html.erb
<p>
  <b>Question:</b>
  <%= @user_answer.question.title %>
</p>

<p>
  <b>Value:</b>
  <%= @user_answer.value %>
</p>