config/routes.rb
Wheretowait::Application.routes.draw do

  match '/dashboard' => 'dashboard#index', :as => :user_root

  resources :flagged_words
  resources :questionnaires do
    resources :user_answers
    get :needs_moderation, :on => :collection
  end
  resources :contacts
  resources :user_answers
  resources :answers
  resources :questions
  resources :question_answers
  resources :locations do
    resources :questionnaires
  end

  resources :members
  devise_for :users

  match '/terms' => 'site#terms', :as => :terms
  match '/privacy' => 'site#privacy', :as => :privacy
  match '/about' => 'site#about', :as => :about
  match '/guidelines' => 'site#guidelines', :as => :guidelines
  match '/faq' => 'site#faq', :as => :faq

  root :to => 'site#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :title, :value

  # relationships
  has_many :user_answers
  has_many :question_answers
  has_many :questions, :through => :question_answers

  # validations
  validates :title, :value, presence: true
  validates :title, length: {in: 1..128}
  validates :value, :numericality => true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :verify_credentials_admin

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private

  def verify_credentials_admin
    # first check if anyone is even checked in
    unless user_signed_in?
      redirect_to new_user_session_path, notice: t(:Need_to_sign_in)
      return
    end
    unless current_user.role=='admin'
      redirect_to root_path, notice: t(:Need_permissions)
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer, :html => {:role => 'form'}) do |f| %>
    <% if @answer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

          <ul>
            <% @answer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title,
                       :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :value %>
      <br/>
      <%= f.text_field :value,
                       :class => 'form-control',
                       :type => :number %>
    </div>

    <div class="form-group">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/answers/edit.html.erb
<% title 'Editing Answer' %>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
</div></div>

app/views/answers/index.html.erb
<% title 'Listing Answers' %>
<% sub_title 'Answers associated with questions.' %>

<div class="table-responsive">
  <table class="table">
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.title %></td>
          <td><%= answer.value %></td>
          <td><%= link_to 'Show', answer %></td>
          <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

<br/>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<% title 'New Answer' %>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
  </div></div>

app/views/answers/show.html.erb
<p>
  <b>Title:</b>
  <%= @answer.title %>
</p>

<p>
  <b>Value:</b>
  <%= @answer.value %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %>