config/routes.rb
Wheretowait::Application.routes.draw do

  match '/dashboard' => 'dashboard#index', :as => :user_root

  resources :flagged_words
  resources :questionnaires do
    resources :user_answers
    get :needs_moderation, :on => :collection
  end
  resources :contacts
  resources :user_answers
  resources :answers
  resources :questions
  resources :question_answers
  resources :locations do
    resources :questionnaires
  end

  resources :members
  devise_for :users

  match '/terms' => 'site#terms', :as => :terms
  match '/privacy' => 'site#privacy', :as => :privacy
  match '/about' => 'site#about', :as => :about
  match '/guidelines' => 'site#guidelines', :as => :guidelines
  match '/faq' => 'site#faq', :as => :faq

  root :to => 'site#index'

end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  attr_accessible :user, :location, :comment, :flagged, :moderated, :user_answers
  before_save :before_save
  #accepts_nested_attributes_for :user_answers

  # relationships
  belongs_to :user
  belongs_to :location
  has_many :user_answers, :dependent => :destroy

  # valdiations
  validates :comment, :user, :location, presence: true
  validates :comment, length: {in: 1..5000}

  # scopes
  scope :flagged, where(:flagged => true)
  scope :not_flagged, where(:flagged => false)
  scope :moderated, where(:moderated => true)
  scope :not_moderated, where(:moderated => false)

  # methods
  def prep_user_answers
    if !user_answers.empty?
      return
    end
    Question.all.each do |q|
      user_answers.push UserAnswer.new :question => q, :questionnaire => self, :location => self.location
    end
  end

  def self.search(search, page, per_page)
    paginate :per_page => per_page, :page => page,
             :conditions => ['comment like ?', "%#{search}%"],
             :order => 'created_at DESC'
  end

  def before_save
    if self.moderated
      return
    end

    flagged_words = FlaggedWord.all
    flagged_words.each do |flagged_word|
      unless " #{self.comment} ".match(/\s+#{flagged_word.word}\s+/i).nil?
        self.flagged = true
        return
      end
    end
  end

end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_filter :verify_credentials_admin, :except => [:new, :show, :create, :destroy]
  before_filter :verify_credentials, :only => [:new, :show, :create, :destroy]
  helper :locations

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.search(params[:search], params[:page], 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questionnaires }
    end
  end

  def needs_moderation
    @questionnaires = Questionnaire.flagged.not_moderated.search(params[:search], params[:page], 30)

    respond_to do |format|
      format.html # needs_moderation.html.erb
      format.json { render json: @questionnaires }
    end
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
    @questionnaire = Questionnaire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questionnaire }
    end
  end

  # GET /questionnaires/new
  # GET /questionnaires/new.json
  def new
    @questionnaire = Questionnaire.new
    if params.include?(:location_id)
      @questionnaire.location = Location.find(params[:location_id])
    end

    @questionnaire.prep_user_answers

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questionnaire }
    end
  end

  # GET /questionnaires/1/edit
  def edit
    @questionnaire = Questionnaire.find(params[:id])
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new :comment => params[:questionnaire][:comment]
    @questionnaire.user = current_user
    @questionnaire.location = Location.find(params[:questionnaire][:location])
    Question.all.each_with_index do |question, index|
      user_answer = UserAnswer.new
      user_answer.question = question
      user_answer.location = @questionnaire.location
      user_answer.questionnaire = @questionnaire
      user_answer.value = params[:questionnaire][:user_answers][index.to_s][:value]
      @questionnaire.user_answers << user_answer
    end

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render json: @questionnaire, status: :created, location: @questionnaire }
      else
        format.html { render action: "new" }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questionnaires/1
  # PUT /questionnaires/1.json
  def update
    @questionnaire = Questionnaire.find(params[:id])

    respond_to do |format|
      if @questionnaire.update_attributes(params[:questionnaire])
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire = Questionnaire.find(params[:id])
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to user_root_path }
      format.json { head :no_content }
    end
  end

  private

  def verify_credentials_admin
    # first check if anyone is even checked in
    unless user_signed_in?
      redirect_to new_user_session_path, notice: t(:Need_to_sign_in)
      return
    end
    unless current_user.role=='admin'
      redirect_to root_path, notice: t(:Need_permissions)
    end
  end

  def verify_credentials
    # first check if anyone is even checked in
    unless user_signed_in?
      redirect_to new_user_session_path, notice: t(:Need_to_sign_in)
      return
    end
  end

end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/questionnaires/_form.html.erb
<%= form_for(@questionnaire, :html => {:role => 'form'}) do |f| %>
    <% if @questionnaire.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionaire from being saved:</h2>

          <ul>
            <% @questionnaire.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if !user_signed_in? %>
        <div class="form-group">
          <%= f.label :user %>
          <br/>
          <%= f.text_field :user, :class => 'form-control' %>
        </div>
    <% end %>
    <% if @questionnaire.location.nil? %>
        <div class="form-group">
          <%= f.label :location %>
          <br/>
          <%= f.collection_select :location, Location.all, :id, :name, {}, {:class => 'form-control'} %>
        </div>
    <% else %>
        <div class="form-group">
          <%= f.hidden_field :location, :value => @questionnaire.location.id %>
          <%= f.label :location %>
          <div>
            <p class="form-control-static"><%= @questionnaire.location.name %></p>
          </div>
        </div>
    <% end %>

    <% if @questionnaire.created_at.nil? %>
        <h2>Questions</h2>

        <% @questionnaire.user_answers.each_with_index do |user_answer, index| %>
            <%= f.fields_for :user_answers do |answer| %>
                <div class="form-group">
                  <%= answer.label user_answer.question.title %>
                  <% if !user_answer.question.unit.empty? %>
                      (<%= user_answer.question.unit %>)
                  <% end %>
                  <div>
                    <% if user_answer.question.answer_type == 'number' %>
                        <%= answer.text_field :value, :type => :number,
                                              :prompt => user_answer.question.unit,
                                              :class => 'form-control',
                                              :index => index %>
                    <% elsif user_answer.question.answer_type == 'choice' %>
                        <%= answer.select :value,
                                          options_from_collection_for_select(user_answer.question.answers.order(:value), :value, :title),
                                          {:include_blank => false, :prompt => 'Select Answer...'},
                                          {:class => 'form-control', :index => index}
                        %>
                    <% end %>
                  </div>
                </div>
            <% end %>
        <% end %>
    <% else %>
        <h2>Answers</h2>
        <div class="table-responsive">
          <table class="table table-hover">
            <tr>
              <th>Question</th>
              <th>Value</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>

            <% @questionnaire.user_answers.each do |user_answer| %>
                <tr>
                  <td><%= user_answer.question.title %></td>
                  <td><%= user_answer.value %></td>
                  <td><%= link_to 'Show', user_answer %></td>
                  <td><%= link_to 'Edit', edit_user_answer_path(user_answer) %></td>
                  <td><%= link_to 'Destroy', user_answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
                </tr>
            <% end %>
          </table>
        </div>
    <% end %>

    <h2>Comment</h2>
    <div class="form-group">
      <%= f.label :comment %>
      <br/>
      <%= f.text_area :comment, :class => 'form-control', :rows => 5 %>
    </div>

    <% if user_signed_in? && current_user.role == 'admin' %>
        <h2>Moderation</h2>

        <div class="form-group">
          <%= f.label :flagged %>
          <div class="checkbox">
            <%= f.label :flagged do %>
                <%= f.check_box :flagged, :class => 'checkbox' %>
                Flagged
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :moderated %>
          <div class="checkbox">
            <%= f.label :moderated do %>
                <%= f.check_box :moderated, :class => 'checkbox' %>
                Moderated
            <% end %>
          </div>
        </div>
    <% end %>

    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/questionnaires/edit.html.erb
<% title 'Editing Questionnaire' %>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
  </div>
</div>

app/views/questionnaires/index.html.erb
<% title 'Listing Questionnaires' %>
<% sub_title 'Completed Questionnaires about locations.' %>

<div class="table-responsive">
  <table class="table table-striped">
    <tr class="table-header">
      <th>User</th>
      <th>Location</th>
      <th>Created At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @questionnaires.each do |questionnaire| %>
        <tr>
          <td><%= questionnaire.user.email %></td>
          <td><%= questionnaire.location.name %></td>
          <td><%= questionnaire.created_at.to_formatted_s :short %></td>
          <td><%= link_to 'Show', questionnaire %></td>
          <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
          <td><%= link_to 'Destroy', questionnaire, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

<br/>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

<%= will_paginate @questionnaires,
                  :renderer => PaginationListLinkRenderer,
                  :previous_label => '&laquo;',
                  :next_label => '&raquo;',
                  :class => 'pagination' %>

app/views/questionnaires/needs_moderation.html.erb
<% title 'Listing Questionnaires Needing Moderation' %>
<% sub_title 'Completed Questionnaires needing moderation.' %>

<div class="table-responsive">
  <table class="table table-striped">
    <tr class="table-header">
      <th>User</th>
      <th>Location</th>
      <th>Created At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @questionnaires.each do |questionnaire| %>
        <tr>
          <td><%= questionnaire.user.email %></td>
          <td><%= questionnaire.location.name %></td>
          <td><%= questionnaire.created_at.to_formatted_s :short %></td>
          <td><%= link_to 'Show', questionnaire %></td>
          <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
          <td><%= link_to 'Destroy', questionnaire, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

<br/>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

<%= will_paginate @questionnaires,
                  :renderer => PaginationListLinkRenderer,
                  :previous_label => '&laquo;',
                  :next_label => '&raquo;',
                  :class => 'pagination' %>

app/views/questionnaires/new.html.erb
<% title 'New Questionnaire' %>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
  </div>
</div>

app/views/questionnaires/show.html.erb
<% title "Review for #{@questionnaire.location.name}" %>

<h2>Listing Answers</h2>

<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>Question</th>
      <th>Value</th>
      <% if user_signed_in? && current_user.role == 'admin' %>
          <th></th>
          <th></th>
          <th></th>
      <% end %>
    </tr>

    <% @questionnaire.user_answers.each do |user_answer| %>
        <tr>
          <td><%= user_answer.question.title %></td>
          <td><%= show_formatted_result(user_answer.question.unit, user_answer.value).html_safe %></td>
          <% if user_signed_in? && current_user.role == 'admin' %>
              <td><%= link_to 'Show', user_answer %></td>
              <td><%= link_to 'Edit', edit_user_answer_path(user_answer) %></td>
              <td><%= link_to 'Destroy', user_answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
    <% end %>
  </table>
</div>

<% unless @questionnaire.flagged %>
    <h2>Comment</h2>
    <blockquote>
      <p><%= @questionnaire.comment %></p>
      <footer><%= @questionnaire.user.city %>, <%= @questionnaire.user.state %></footer>
    </blockquote>
<% end %>

<% if user_signed_in? && current_user.role == 'admin' %>
    <h2>Moderation</h2>
    <p>
      <b>Moderated:</b>
      <%= @questionnaire.moderated %>
    </p>

    <p>
      <b>Flagged:</b>
      <%= @questionnaire.flagged %>
    </p>
<% end %>