config/routes.rb
Wheretowait::Application.routes.draw do

  match '/dashboard' => 'dashboard#index', :as => :user_root

  resources :flagged_words
  resources :questionnaires do
    resources :user_answers
    get :needs_moderation, :on => :collection
  end
  resources :contacts
  resources :user_answers
  resources :answers
  resources :questions
  resources :question_answers
  resources :locations do
    resources :questionnaires
  end

  resources :members
  devise_for :users

  match '/terms' => 'site#terms', :as => :terms
  match '/privacy' => 'site#privacy', :as => :privacy
  match '/about' => 'site#about', :as => :about
  match '/guidelines' => 'site#guidelines', :as => :guidelines
  match '/faq' => 'site#faq', :as => :faq

  root :to => 'site#index'

end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base
  attr_accessible :answer, :question

  # relationships
  belongs_to :question
  belongs_to :answer

  # validations
  validates :question, :answer, presence: true
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
  # GET /question_answers
  # GET /question_answers.json
  def index
    @question_answers = QuestionAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_answers }
    end
  end

  # GET /question_answers/1
  # GET /question_answers/1.json
  def show
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/new
  # GET /question_answers/new.json
  def new
    @question_answer = QuestionAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_answer }
    end
  end

  # GET /question_answers/1/edit
  def edit
    @question_answer = QuestionAnswer.find(params[:id])
  end

  # POST /question_answers
  # POST /question_answers.json
  def create
    @question_answer = QuestionAnswer.new(params[:question_answer])

    respond_to do |format|
      if @question_answer.save
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully created.' }
        format.json { render json: @question_answer, status: :created, location: @question_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_answers/1
  # PUT /question_answers/1.json
  def update
    @question_answer = QuestionAnswer.find(params[:id])

    respond_to do |format|
      if @question_answer.update_attributes(params[:question_answer])
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_answers/1
  # DELETE /question_answers/1.json
  def destroy
    @question_answer = QuestionAnswer.find(params[:id])
    @question_answer.destroy

    respond_to do |format|
      format.html { redirect_to question_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/views/question_answers/_form.html.erb
<%= form_for(@question_answer, :html => {:role => 'form'}) do |f| %>
    <% if @question_answer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question_answer.errors.count, "error") %> prohibited this question_answer from being
            saved:</h2>

          <ul>
            <% @question_answer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :question %>
      <br/>
      <%= f.text_field :question, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :answer %>
      <br/>
      <%= f.text_field :answer, :class => 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/question_answers/edit.html.erb
<h1>Editing question_answer</h1>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>

  </div>
</div>

app/views/question_answers/index.html.erb
<h1>Listing question_answers</h1>

<table class="table table-striped">
  <tr class="table-header">
    <th>Question</th>
    <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @question_answers.each do |question_answer| %>
      <tr>
        <td><%= question_answer.question %></td>
        <td><%= question_answer.answer %></td>
        <td><%= link_to 'Show', question_answer %></td>
        <td><%= link_to 'Edit', edit_question_answer_path(question_answer) %></td>
        <td><%= link_to 'Destroy', question_answer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Question answer', new_question_answer_path %>

app/views/question_answers/new.html.erb
<h1>New question_answer</h1>

<div class="row">
  <div class="col-sm-6">
<%= render 'form' %>
  </div>
</div>

app/views/question_answers/show.html.erb
<p>
  <b>Question:</b>
  <%= @question_answer.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @question_answer.answer %>
</p>


<%= link_to 'Edit', edit_question_answer_path(@question_answer) %> |
<%= link_to 'Back', question_answers_path %>